### ISSUE TITLE
你好，我除了cpu是i3的之外，其他的都和你几乎一样，但是却无法使用这个efi，我应该如何配置才是正确的？

### ISSUE THREAD

**Issue by patrickgao2013** [JHXue/hackintosh-efi#4]

**Comment by BlankXue** [comment]
我只能给你一个思路。
我的思路：首先了解一下，clover 怎么配置。（https://blog.daliansky.net/clover-user-manual.html）
然后比较别人   i3 的 clover.plist。与我的的 clover.plist 区别在哪里。
然后 try…… try。
有句话与君共勉。“黑苹果”，永远没有完美，只有折腾。多尝试，多试。
